from collections.abc import Sequence
from typing import Protocol
from uuid import UUID

from knowledge_os.domain.entities import (
    ChunkEmbedding,
    Conversation,
    Document,
    DocumentChunk,
    DocumentVersion,
    LlmUsage,
    Message,
    Organization,
    OrganizationMembership,
    Project,
    ProjectMembership,
    RefreshSession,
    User,
    WorkflowEvent,
    WorkflowRun,
)


class UserRepository(Protocol):
    async def add(self, user: User) -> None: ...
    async def save(self, user: User) -> None: ...
    async def get_by_id(self, user_id: UUID) -> User | None: ...
    async def get_by_email(self, email: str) -> User | None: ...


class OrganizationRepository(Protocol):
    async def add(self, organization: Organization) -> None: ...
    async def add_membership(self, membership: OrganizationMembership) -> None: ...
    async def list_for_user(self, user_id: UUID) -> Sequence[Organization]: ...
    async def user_role(self, organization_id: UUID, user_id: UUID) -> str | None: ...


class RefreshSessionRepository(Protocol):
    async def add(self, session: RefreshSession) -> None: ...
    async def save(self, session: RefreshSession) -> None: ...
    async def get_by_id(self, session_id: UUID) -> RefreshSession | None: ...
    async def revoke_family(self, family_id: UUID) -> None: ...


class ProjectRepository(Protocol):
    async def add(self, project: Project) -> None: ...
    async def save(self, project: Project) -> None: ...
    async def add_membership(self, membership: ProjectMembership) -> None: ...
    async def get_for_user(self, project_id: UUID, user_id: UUID) -> Project | None: ...
    async def list_for_user(
        self, organization_id: UUID, user_id: UUID, limit: int
    ) -> Sequence[Project]: ...
    async def user_role(self, project_id: UUID, user_id: UUID) -> str | None: ...


class DocumentRepository(Protocol):
    async def add(self, document: Document) -> None: ...
    async def save(self, document: Document) -> None: ...
    async def get_by_id(self, document_id: UUID, user_id: UUID) -> Document | None: ...
    async def list_for_project(
        self, organization_id: UUID, project_id: UUID, user_id: UUID, limit: int
    ) -> Sequence[Document]: ...
    async def add_version(self, version: DocumentVersion) -> None: ...
    async def save_version(self, version: DocumentVersion) -> None: ...
    async def get_version_by_id(
        self, version_id: UUID, user_id: UUID
    ) -> DocumentVersion | None: ...

    async def get_version_by_number(
        self, document_id: UUID, version_number: int, user_id: UUID
    ) -> DocumentVersion | None: ...

    async def list_versions(
        self, document_id: UUID, user_id: UUID
    ) -> Sequence[DocumentVersion]: ...


class ConversationRepository(Protocol):
    async def add(self, conversation: Conversation) -> None: ...
    async def save(self, conversation: Conversation) -> None: ...
    async def get_by_id(self, conversation_id: UUID, user_id: UUID) -> Conversation | None: ...
    async def list_for_project(
        self, organization_id: UUID, project_id: UUID, user_id: UUID, limit: int
    ) -> Sequence[Conversation]: ...

    async def add_message(self, message: Message) -> None: ...
    async def save_message(self, message: Message) -> None: ...
    async def list_messages(self, conversation_id: UUID, user_id: UUID) -> Sequence[Message]: ...


class LlmUsageRepository(Protocol):
    async def add(self, usage: LlmUsage) -> None: ...
    async def get_by_id(self, usage_id: UUID) -> LlmUsage | None: ...


class WorkflowRunRepository(Protocol):
    async def add(self, run: WorkflowRun) -> None: ...
    async def save(self, run: WorkflowRun) -> None: ...
    async def get_by_id(self, run_id: UUID) -> WorkflowRun | None: ...
    async def get_by_workflow_id(self, workflow_id: str) -> WorkflowRun | None: ...
    async def list_for_resource(
        self, resource_type: str, resource_id: UUID
    ) -> Sequence[WorkflowRun]: ...


class WorkflowEventRepository(Protocol):
    async def add(self, event: WorkflowEvent) -> None: ...
    async def list_for_run(self, workflow_run_id: UUID) -> Sequence[WorkflowEvent]: ...


class DocumentChunkRepository(Protocol):
    async def add_batch(self, chunks: Sequence[DocumentChunk]) -> None: ...
    async def list_for_version(self, version_id: UUID) -> Sequence[DocumentChunk]: ...
    async def delete_for_version(self, version_id: UUID) -> None: ...
    async def list_by_ids(self, ids: Sequence[UUID]) -> Sequence[DocumentChunk]: ...


class ChunkEmbeddingRepository(Protocol):
    async def add_batch(self, embeddings: Sequence[ChunkEmbedding]) -> None: ...
    async def list_for_version(
        self, version_id: UUID, embedding_version: int
    ) -> Sequence[ChunkEmbedding]: ...
    async def delete_for_version(self, version_id: UUID, embedding_version: int) -> None: ...


class UnitOfWork(Protocol):
    users: UserRepository
    organizations: OrganizationRepository
    refresh_sessions: RefreshSessionRepository
    projects: ProjectRepository
    documents: DocumentRepository
    conversations: ConversationRepository
    llm_usage: LlmUsageRepository
    workflow_runs: WorkflowRunRepository
    workflow_events: WorkflowEventRepository
    document_chunks: DocumentChunkRepository
    chunk_embeddings: ChunkEmbeddingRepository

    async def __aenter__(self) -> "UnitOfWork": ...
    async def __aexit__(self, exc_type: object, exc: object, tb: object) -> None: ...
    async def commit(self) -> None: ...
    async def flush(self) -> None: ...
