from collections.abc import Sequence
from typing import Protocol
from uuid import UUID

from knowledge_os.domain.entities import (
    Organization,
    OrganizationMembership,
    Project,
    ProjectMembership,
    RefreshSession,
    User,
)


class UserRepository(Protocol):
    async def add(self, user: User) -> None: ...
    async def save(self, user: User) -> None: ...
    async def get_by_id(self, user_id: UUID) -> User | None: ...
    async def get_by_email(self, email: str) -> User | None: ...


class OrganizationRepository(Protocol):
    async def add(self, organization: Organization) -> None: ...
    async def add_membership(self, membership: OrganizationMembership) -> None: ...
    async def list_for_user(self, user_id: UUID) -> Sequence[Organization]: ...
    async def user_role(self, organization_id: UUID, user_id: UUID) -> str | None: ...


class RefreshSessionRepository(Protocol):
    async def add(self, session: RefreshSession) -> None: ...
    async def save(self, session: RefreshSession) -> None: ...
    async def get_by_id(self, session_id: UUID) -> RefreshSession | None: ...
    async def revoke_family(self, family_id: UUID) -> None: ...


class ProjectRepository(Protocol):
    async def add(self, project: Project) -> None: ...
    async def save(self, project: Project) -> None: ...
    async def add_membership(self, membership: ProjectMembership) -> None: ...
    async def get_for_user(self, project_id: UUID, user_id: UUID) -> Project | None: ...
    async def list_for_user(
        self, organization_id: UUID, user_id: UUID, limit: int
    ) -> Sequence[Project]: ...
    async def user_role(self, project_id: UUID, user_id: UUID) -> str | None: ...


class UnitOfWork(Protocol):
    users: UserRepository
    organizations: OrganizationRepository
    refresh_sessions: RefreshSessionRepository
    projects: ProjectRepository

    async def __aenter__(self) -> "UnitOfWork": ...
    async def __aexit__(self, exc_type: object, exc: object, tb: object) -> None: ...
    async def commit(self) -> None: ...
