"""add_ingestion_metrics_and_metadata

Revision ID: 274853379664
Revises: ccf798388b9c
Create Date: 2026-06-07 01:26:11.267165
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "274853379664"
down_revision: str | None = "ccf798388b9c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("document_chunks", sa.Column("char_count", sa.Integer(), nullable=False))
    op.add_column(
        "document_versions", sa.Column("extracted_characters", sa.Integer(), nullable=True)
    )
    op.add_column("document_versions", sa.Column("page_count", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("document_versions", "page_count")
    op.drop_column("document_versions", "extracted_characters")
    op.drop_column("document_chunks", "char_count")
    # ### end Alembic commands ###
