"""create_chunk_embeddings_table

Revision ID: 2f32957df35e
Revises: 274853379664
Create Date: 2026-06-07 01:39:01.793117
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "2f32957df35e"
down_revision: str | None = "274853379664"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chunk_embeddings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("document_chunk_id", sa.UUID(), nullable=False),
        sa.Column("provider", sa.String(length=100), nullable=False),
        sa.Column("model", sa.String(length=100), nullable=False),
        sa.Column("embedding_dimension", sa.Integer(), nullable=False),
        sa.Column("embedding_version", sa.Integer(), nullable=False),
        sa.Column("qdrant_point_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["document_chunk_id"], ["document_chunks.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "document_chunk_id", "embedding_version", name="uq_chunk_embedding_version"
        ),
    )
    op.create_index(
        "ix_chunk_embeddings_chunk_id", "chunk_embeddings", ["document_chunk_id"], unique=False
    )
    op.create_index(
        "ix_chunk_embeddings_org_id", "chunk_embeddings", ["organization_id"], unique=False
    )
    op.create_index(
        "ix_chunk_embeddings_version", "chunk_embeddings", ["embedding_version"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_chunk_embeddings_version", table_name="chunk_embeddings")
    op.drop_index("ix_chunk_embeddings_org_id", table_name="chunk_embeddings")
    op.drop_index("ix_chunk_embeddings_chunk_id", table_name="chunk_embeddings")
    op.drop_table("chunk_embeddings")
    # ### end Alembic commands ###
