"""create_document_chunks_table

Revision ID: ccf798388b9c
Revises: 35bf1154174d
Create Date: 2026-06-07 01:03:55.148560
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "ccf798388b9c"
down_revision: str | None = "35bf1154174d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "document_chunks",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("version_id", sa.UUID(), nullable=False),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("char_offset", sa.Integer(), nullable=False),
        sa.Column("token_count", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["version_id"], ["document_versions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("version_id", "chunk_index", name="uq_document_chunk_version_index"),
    )
    op.create_index(
        "ix_document_chunks_org_doc",
        "document_chunks",
        ["organization_id", "document_id"],
        unique=False,
    )
    op.create_index(
        "ix_document_chunks_version_id", "document_chunks", ["version_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_document_chunks_version_id", table_name="document_chunks")
    op.drop_index("ix_document_chunks_org_doc", table_name="document_chunks")
    op.drop_table("document_chunks")
    # ### end Alembic commands ###
